### ISSUE TITLE
Support VS2015

### ISSUE THREAD

**Issue by mongeon** [tanathos/WhereAmI#1]
Since I love this extension and now I'm running VS2015, it would be nice if WhereAmI could be ported to the new Visual Studio version.

**Comment by tanathos** [comment]
It's on the plans! :D 
I'm just waiting to have some time to work on it.

**Comment by mongeon** [comment]
Great! I've tried unsuccessfully to make the changes, theses VS Extension are not easy to work on...

**Comment by tanathos** [comment]
The extension is now available for VS2015: 
https://github.com/tanathos/WhereAmI2015 
https://visualstudiogallery.msdn.microsoft.com/3bc7cf65-3a0b-416b-9e2c-65fc0ef23205
